services:

  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=jodel
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - '3306:3306'
    volumes:
      - db-volume:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  jodel-survey-app:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - IP=0.0.0.0
      - PORT=8080
      - API_ROOT=/v1
      - DB_DIALECT=mysql
      - DB_NAME=jodel
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=mauFJcuf5dhRMQrjj
volumes:
  db-volume:
    driver: local
