services:
  jodel-survey-app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "./storage:/storage"
    environment:
      - IP=0.0.0.0
      - PORT=8080
      - API_ROOT=/v1
      - DB_DIALECT=sqlite
      - DB_STORAGE=/storage/database.sqlite
